name: clover_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.2.0
  connectivity_plus: ^2.3.6
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.22.0
  get: ^4.6.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSemiBold.ttf
          weight: 600
    - family: Cabin
      fonts:
        - asset: assets/fonts/CabinRegular.ttf
          weight: 400
    - family: Merriweather
      fonts:
        - asset: assets/fonts/MerriweatherRegular.ttf
          weight: 400
    - family: Overpass
      fonts:
        - asset: assets/fonts/OverpassBold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSansRegular.ttf
          weight: 400
    - family: Arvo
      fonts:
        - asset: assets/fonts/Arvo.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
